fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

user:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/UserController.php"
    options:
        expose: true

mission:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/MissionController.php"
    options:
        expose: true

missionType:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/MissionTypeController.php"
    options:
        expose: true

monster:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/MonsterController.php"
    options:
        expose: true

monsterType:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/MonsterTypeController.php"
    options:
        expose: true

map:
    prefix: /xenobladex/api
    type:     rest
    resource: "@AppBundle/Controller/MapController.php"
    options:
        expose: true

attachment:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/AttachmentController.php"
    options:
        expose: true

person:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/PersonController.php"
    options:
        expose: true

faq:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/FaqController.php"
    options:
        expose: true

mapmarker:
    prefix: /xenobladex/api
    type:     rest
    resource: "@AppBundle/Controller/MapmarkerController.php"
    options:
        expose: true

material:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/MaterialController.php"
    options:
        expose: true

collectible:
    prefix: /xenobladex
    type:     rest
    resource: "@AppBundle/Controller/CollectibleController.php"
    options:
        expose: true

show_attachment:
    path: /xenobladex/attachment/{id}
    defaults: { _controller: AppBundle:Attachment:showAttachment }


remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirect:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]