user:
    prefix: /api
    type:     rest
    resource: "@AppBundle/Controller/RestController/UserController.php"

mission:
    prefix: /api
    type:     rest
    resource: "@AppBundle/Controller/RestController/MissionController.php"

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirect:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]