security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        rest_webservice:
            pattern: /api/.*
            stateless: true
            form_login: false
            provider: fos_userbundle
            http_basic: ~

    access_control:
        - { path: ^/api/admin/, role: ROLE_ADMIN }