# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  jms_serializer.object_constructor:
          alias: jms_serializer.doctrine_object_constructor
          public: false

  jms_serializer.doctrine_object_constructor:
          class:        %jms_serializer.doctrine_object_constructor.class%
          public:       false
          arguments:    ["@doctrine", "@jms_serializer.unserialize_object_constructor"]

  app.form.mission.type:
      class: AppBundle\Form\MissionType
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: form.type }
