# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  jms_serializer.object_constructor:
          alias: jms_serializer.doctrine_object_constructor
          public: false

  jms_serializer.doctrine_object_constructor:
          class:        %jms_serializer.doctrine_object_constructor.class%
          public:       false
          arguments:    ["@doctrine", "@jms_serializer.unserialize_object_constructor"]

  app.serializer.handler.related_entity:
     class: AppBundle\Serializer\Handler\RelatedEntityHandler
     arguments: ["@doctrine.orm.entity_manager"]
     tags:
         - { name: jms_serializer.subscribing_handler }

  app.service.attachment:
     class: AppBundle\Service\AttachmentService

  app.controller.attachment:
     class: AppBundle\Controller\AttachmentController
     arguments: [app.service.attachment]

  fos_user.doctrine_registry:
      alias: doctrine